### ISSUE TITLE
Only rerun updated validators

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/module-compilation#237]
To check if we have up to date compilation results, we use a single hash on the contents of the file combined with all the version numbers of the validators. This means when any one of the validators is updated, the hash is invalidated and all validators are rerun on the file.
In reality, often only one of the four validators we use is updated, which means we could reuse the cached output of the other three instead of rerunning them. This is especially an issue when a new release with an updated validator is deployed. It takes days for all modules to be recompiled with every validator and during this time the CPU usage is maxed out. By only rerunning the updated validator, this time could be significantly reduced.
For each file, we should remember the latest version number of each validator it was compiled with. A module should only be recompiled by a validator if the current version number of the validator is higher than the version we have remembered.

**Comment by SlavomirMazurPantheon** [comment]
This sounds like a good improvement and and can save a lot resources. 
We can either compare validators versions as raw test strings or maybe store hash for individual validator - maybe it would be nice to compare the speed, whether the generation of separate hashes will not slow down the program.

**Comment by SlavomirMazurPantheon** [comment]
@Fagtoy currently we are using file_hasher.py which takes content of the file, adds versions of all the validators used (it adds two strings together) and then create one hash from this string, which is stored.

Every time if one validator is updated, it needs to be re-validated by all the validators.
What we want to achieve is that we somehow store information of validator version used separately, so module will be re-validated only by updated validator.
