### ISSUE TITLE
Run validators on the same file processed by the parse and populate pipeline

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/module-compilation#248]
While compiling modules, the current approach is that every time when a module with a specific name and revision and a new hash is encountered, the compilation results from this version of the module overwrite the compilation results for that name and revision stored in redis. This is a problem, because we can not be sure that the version compiled last is the same as the version of the module the backend has accepted (parsed and copied to `/var/yang/all_modules`).

One way I can think of resolving this is that during regular runs, the `compile_modules.py` script will not upload any of the results to redis. After the HTML and JSON reports have been generated for all the directories we currently compile, the script would be run again with a different setting on the `all_modules` directory. This is when it would upload the compilation results to redis. Almost all of these would already have been encountered in one of the directries we've already compiled, so we'd only need to pull out the cached data and send it to redis. The rest of the modules would be compiled normally.

**Comment by Fagtoy** [comment]
The more detailed explanation of this issue:
```
So there's these two files https://github.com/Juniper/yang/blob/master/17.2/17.2R1/junos/show-rsvp.yang, https://github.com/Juniper/yang/blob/master/17.3/17.3R1/junos-es/show-rsvp.yang.
Both of the modules are named show-rsvp and the revision in both of them is 2017-01-01, but the contents are very different.
Currently what the backend should do is take the first one it encounters, put it in the all_modules directory, and from that point on ignore any different files with the same name and revision. So populate.py will upload data parsed out of the first module to redis.
compile_modules,py will first find the first one, upload the compilation data for show-rsvp@2017-01-01 to redis, then it will find the second one and overwrite the compilation data for show-rsvp@2017-01-01 again. So now we end up with compilation data for the second file and parse and populate data for the first file mixed in the same redis entry.
```
